export default defineAppConfig({
  addressConfig: [
    {
      text: '臺北市',
      value: '1',
      cityEngName: 'Taipei City',
      children: [
        { value: '100', text: '中正區', areaEngName: 'Zhongzheng Dist.' },
        { value: '103', text: '大同區', areaEngName: 'Datong Dist.' },
        { value: '104', text: '中山區', areaEngName: 'Zhongshan Dist.' },
        { value: '105', text: '松山區', areaEngName: 'Songshan Dist.' },
        { value: '106', text: '大安區', areaEngName: 'Da’an Dist.' },
        { value: '108', text: '萬華區', areaEngName: 'Wanhua Dist.' },
        { value: '110', text: '信義區', areaEngName: 'Xinyi Dist.' },
        { value: '111', text: '士林區', areaEngName: 'Shilin Dist.' },
        { value: '112', text: '北投區', areaEngName: 'Beitou Dist.' },
        { value: '114', text: '內湖區', areaEngName: 'Neihu Dist.' },
        { value: '115', text: '南港區', areaEngName: 'Nangang Dist.' },
        { value: '116', text: '文山區', areaEngName: 'Wenshan Dist.' }
      ]
    },
    {
      text: '基隆市',
      value: '2',
      cityEngName: 'Keelung City',
      children: [
        { value: '200', text: '仁愛區', areaEngName: 'Ren’ai Dist.' },
        { value: '201', text: '信義區', areaEngName: 'Xinyi Dist.' },
        { value: '202', text: '中正區', areaEngName: 'Zhongzheng Dist.' },
        { value: '203', text: '中山區', areaEngName: 'Zhongshan Dist.' },
        { value: '204', text: '安樂區', areaEngName: 'Anle Dist.' },
        { value: '205', text: '暖暖區', areaEngName: 'Nuannuan Dist.' },
        { value: '206', text: '七堵區', areaEngName: 'Qidu Dist.' }
      ]
    },
    {
      text: '新北市',
      value: '3',
      cityEngName: 'New Taipei City',
      children: [
        { value: '207', text: '萬里區', areaEngName: 'Wanli Dist.' },
        { value: '208', text: '金山區', areaEngName: 'Jinshan Dist.' },
        { value: '220', text: '板橋區', areaEngName: 'Banqiao Dist.' },
        { value: '221', text: '汐止區', areaEngName: 'Xizhi Dist.' },
        { value: '222', text: '深坑區', areaEngName: 'Shenkeng Dist.' },
        { value: '223', text: '石碇區', areaEngName: 'Shiding Dist.' },
        { value: '224', text: '瑞芳區', areaEngName: 'Ruifang Dist.' },
        { value: '226', text: '平溪區', areaEngName: 'Pingxi Dist.' },
        { value: '227', text: '雙溪區', areaEngName: 'Shuangxi Dist.' },
        { value: '228', text: '貢寮區', areaEngName: 'Gongliao Dist.' },
        { value: '231', text: '新店區', areaEngName: 'Xindian Dist.' },
        { value: '232', text: '坪林區', areaEngName: 'Pinglin Dist.' },
        { value: '233', text: '烏來區', areaEngName: 'Wulai Dist.' },
        { value: '234', text: '永和區', areaEngName: 'Yonghe Dist.' },
        { value: '235', text: '中和區', areaEngName: 'Zhonghe Dist.' },
        { value: '236', text: '土城區', areaEngName: 'Tucheng Dist.' },
        { value: '237', text: '三峽區', areaEngName: 'Sanxia Dist.' },
        { value: '238', text: '樹林區', areaEngName: 'Shulin Dist.' },
        { value: '239', text: '鶯歌區', areaEngName: 'Yingge Dist.' },
        { value: '241', text: '三重區', areaEngName: 'Sanchong Dist.' },
        { value: '242', text: '新莊區', areaEngName: 'Xinzhuang Dist.' },
        { value: '243', text: '泰山區', areaEngName: 'Taishan Dist.' },
        { value: '244', text: '林口區', areaEngName: 'Linkou Dist.' },
        { value: '247', text: '蘆洲區', areaEngName: 'Luzhou Dist.' },
        { value: '248', text: '五股區', areaEngName: 'Wugu Dist.' },
        { value: '249', text: '八里區', areaEngName: 'Bali Dist.' },
        { value: '251', text: '淡水區', areaEngName: 'Tamsui Dist.' },
        { value: '252', text: '三芝區', areaEngName: 'Sanzhi Dist.' },
        { value: '253', text: '石門區', areaEngName: 'Shimen Dist.' }
      ]
    },
    {
      text: '連江縣',
      value: '4',
      cityEngName: 'Lienchiang County',
      children: [
        { value: '209', text: '南竿鄉', areaEngName: 'Nangan Township' },
        { value: '210', text: '北竿鄉', areaEngName: 'Beigan Township' },
        { value: '211', text: '莒光鄉', areaEngName: 'Juguang Township' },
        { value: '212', text: '東引鄉', areaEngName: 'Dongyin Township' }
      ]
    },
    {
      text: '宜蘭縣',
      value: '5',
      cityEngName: 'Yilan County',
      children: [
        { value: '260', text: '宜蘭市', areaEngName: 'Yilan City' },
        { value: '263', text: '壯圍鄉', areaEngName: 'Zhuangwei Township' },
        { value: '261', text: '頭城鎮', areaEngName: 'Toucheng Township' },
        { value: '262', text: '礁溪鄉', areaEngName: 'Jiaoxi Township' },
        { value: '264', text: '員山鄉', areaEngName: 'Yuanshan Township' },
        { value: '265', text: '羅東鎮', areaEngName: 'Luodong Township' },
        { value: '266', text: '三星鄉', areaEngName: 'Sanxing Township' },
        { value: '267', text: '大同鄉', areaEngName: 'Datong Township' },
        { value: '268', text: '五結鄉', areaEngName: 'Wujie Township' },
        { value: '269', text: '冬山鄉', areaEngName: 'Dongshan Township' },
        { value: '270', text: '蘇澳鎮', areaEngName: 'Su’ao Township' },
        { value: '272', text: '南澳鄉', areaEngName: 'Nan’ao Township' },
        { value: '290', text: '釣魚臺', areaEngName: 'Diaoyutai' }
      ]
    },
    {
      text: '釣魚臺',
      value: '6',
      cityEngName: 'Diauyutai',
      children: [{ value: '290', text: '釣魚臺', areaEngName: 'Diaoyutai' }]
    },
    {
      text: '新竹市',
      value: '7',
      cityEngName: 'Hsinchu City',
      children: [
        { value: '300', text: '東區', areaEngName: 'East Dist.' },
        { value: '300', text: '北區', areaEngName: 'North Dist.' },
        { value: '300', text: '香山區', areaEngName: 'Xiangshan Dist.' }
      ]
    },
    {
      text: '新竹縣',
      value: '8',
      cityEngName: 'Hsinchu County',
      children: [
        { value: '308', text: '寶山鄉', areaEngName: 'Baoshan Township' },
        { value: '302', text: '竹北市', areaEngName: 'Zhubei City' },
        { value: '303', text: '湖口鄉', areaEngName: 'Hukou Township' },
        { value: '304', text: '新豐鄉', areaEngName: 'Xinfeng Township' },
        { value: '305', text: '新埔鎮', areaEngName: 'Xinpu Township' },
        { value: '306', text: '關西鎮', areaEngName: 'Guanxi Township' },
        { value: '307', text: '芎林鄉', areaEngName: 'Qionglin Township' },
        { value: '310', text: '竹東鎮', areaEngName: 'Zhudong Township' },
        { value: '311', text: '五峰鄉', areaEngName: 'Wufeng Township' },
        { value: '312', text: '橫山鄉', areaEngName: 'Hengshan Township' },
        { value: '313', text: '尖石鄉', areaEngName: 'Jianshi Township' },
        { value: '314', text: '北埔鄉', areaEngName: 'Beipu Township' },
        { value: '315', text: '峨眉鄉', areaEngName: 'Emei Township' }
      ]
    },
    {
      text: '桃園市',
      value: '9',
      cityEngName: 'Taoyuan City',
      children: [
        { value: '320', text: '中壢區', areaEngName: 'Zhongli Dist.' },
        { value: '324', text: '平鎮區', areaEngName: 'Pingzhen Dist.' },
        { value: '325', text: '龍潭區', areaEngName: 'Longtan Dist.' },
        { value: '326', text: '楊梅區', areaEngName: 'Yangmei Dist.' },
        { value: '327', text: '新屋區', areaEngName: 'Xinwu Dist.' },
        { value: '328', text: '觀音區', areaEngName: 'Guanyin Dist.' },
        { value: '330', text: '桃園區', areaEngName: 'Taoyuan Dist.' },
        { value: '333', text: '龜山區', areaEngName: 'Guishan Dist.' },
        { value: '334', text: '八德區', areaEngName: 'Bade Dist.' },
        { value: '335', text: '大溪區', areaEngName: 'Daxi Dist.' },
        { value: '336', text: '復興區', areaEngName: 'Fuxing Dist.' },
        { value: '337', text: '大園區', areaEngName: 'Dayuan Dist.' },
        { value: '338', text: '蘆竹區', areaEngName: 'Luzhu Dist.' }
      ]
    },
    {
      text: '苗栗縣',
      value: '10',
      cityEngName: 'Miaoli County',
      children: [
        { value: '350', text: '竹南鎮', areaEngName: 'Zhunan Township' },
        { value: '351', text: '頭份市', areaEngName: 'Toufen City' },
        { value: '352', text: '三灣鄉', areaEngName: 'Sanwan Township' },
        { value: '353', text: '南庄鄉', areaEngName: 'Nanzhuang Township' },
        { value: '354', text: '獅潭鄉', areaEngName: 'Shitan Township' },
        { value: '356', text: '後龍鎮', areaEngName: 'Houlong Township' },
        { value: '357', text: '通霄鎮', areaEngName: 'Tongxiao Township' },
        { value: '358', text: '苑裡鎮', areaEngName: 'Yuanli Township' },
        { value: '360', text: '苗栗市', areaEngName: 'Miaoli City' },
        { value: '361', text: '造橋鄉', areaEngName: 'Zaoqiao Township' },
        { value: '362', text: '頭屋鄉', areaEngName: 'Touwu Township' },
        { value: '363', text: '公館鄉', areaEngName: 'Gongguan Township' },
        { value: '364', text: '大湖鄉', areaEngName: 'Dahu Township' },
        { value: '365', text: '泰安鄉', areaEngName: 'Tai’an Township' },
        { value: '366', text: '銅鑼鄉', areaEngName: 'Tongluo Township' },
        { value: '367', text: '三義鄉', areaEngName: 'Sanyi Township' },
        { value: '368', text: '西湖鄉', areaEngName: 'Xihu Township' },
        { value: '369', text: '卓蘭鎮', areaEngName: 'Zhuolan Township' }
      ]
    },
    {
      text: '臺中市',
      value: '11',
      cityEngName: 'Taichung City',
      children: [
        { value: '400', text: '中區', areaEngName: 'Central Dist.' },
        { value: '401', text: '東區', areaEngName: 'East Dist.' },
        { value: '402', text: '南區', areaEngName: 'South Dist.' },
        { value: '403', text: '西區', areaEngName: 'West Dist.' },
        { value: '404', text: '北區', areaEngName: 'North Dist.' },
        { value: '406', text: '北屯區', areaEngName: 'Beitun Dist.' },
        { value: '407', text: '西屯區', areaEngName: 'Xitun Dist.' },
        { value: '408', text: '南屯區', areaEngName: 'Nantun Dist.' },
        { value: '411', text: '太平區', areaEngName: 'Taiping Dist.' },
        { value: '412', text: '大里區', areaEngName: 'Dali Dist.' },
        { value: '413', text: '霧峰區', areaEngName: 'Wufeng Dist.' },
        { value: '414', text: '烏日區', areaEngName: 'Wuri Dist.' },
        { value: '420', text: '豐原區', areaEngName: 'Fengyuan Dist.' },
        { value: '421', text: '后里區', areaEngName: 'Houli Dist.' },
        { value: '422', text: '石岡區', areaEngName: 'Shigang Dist.' },
        { value: '423', text: '東勢區', areaEngName: 'Dongshi Dist.' },
        { value: '424', text: '和平區', areaEngName: 'Heping Dist.' },
        { value: '426', text: '新社區', areaEngName: 'Xinshe Dist.' },
        { value: '427', text: '潭子區', areaEngName: 'Tanzi Dist.' },
        { value: '428', text: '大雅區', areaEngName: 'Daya Dist.' },
        { value: '429', text: '神岡區', areaEngName: 'Shengang Dist.' },
        { value: '432', text: '大肚區', areaEngName: 'Dadu Dist.' },
        { value: '433', text: '沙鹿區', areaEngName: 'Shalu Dist.' },
        { value: '434', text: '龍井區', areaEngName: 'Longjing Dist.' },
        { value: '435', text: '梧棲區', areaEngName: 'Wuqi Dist.' },
        { value: '436', text: '清水區', areaEngName: 'Qingshui Dist.' },
        { value: '437', text: '大甲區', areaEngName: 'Dajia Dist.' },
        { value: '438', text: '外埔區', areaEngName: 'Waipu Dist.' },
        { value: '439', text: '大安區', areaEngName: 'Da’an Dist.' }
      ]
    },
    {
      text: '彰化縣',
      value: '12',
      cityEngName: 'Changhua County',
      children: [
        { value: '500', text: '彰化市', areaEngName: 'Changhua City' },
        { value: '502', text: '芬園鄉', areaEngName: 'Fenyuan Township' },
        { value: '503', text: '花壇鄉', areaEngName: 'Huatan Township' },
        { value: '504', text: '秀水鄉', areaEngName: 'Xiushui Township' },
        { value: '505', text: '鹿港鎮', areaEngName: 'Lukang Township' },
        { value: '506', text: '福興鄉', areaEngName: 'Fuxing Township' },
        { value: '507', text: '線西鄉', areaEngName: 'Xianxi Township' },
        { value: '508', text: '和美鎮', areaEngName: 'Hemei Township' },
        { value: '509', text: '伸港鄉', areaEngName: 'Shengang Township' },
        { value: '510', text: '員林市', areaEngName: 'Yuanlin City' },
        { value: '511', text: '社頭鄉', areaEngName: 'Shetou Township' },
        { value: '512', text: '永靖鄉', areaEngName: 'Yongjing Township' },
        { value: '513', text: '埔心鄉', areaEngName: 'Puxin Township' },
        { value: '514', text: '溪湖鎮', areaEngName: 'Xihu Township' },
        { value: '515', text: '大村鄉', areaEngName: 'Dacun Township' },
        { value: '516', text: '埔鹽鄉', areaEngName: 'Puyan Township' },
        { value: '520', text: '田中鎮', areaEngName: 'Tianzhong Township' },
        { value: '521', text: '北斗鎮', areaEngName: 'Beidou Township' },
        { value: '522', text: '田尾鄉', areaEngName: 'Tianwei Township' },
        { value: '523', text: '埤頭鄉', areaEngName: 'Pitou Township' },
        { value: '524', text: '溪州鄉', areaEngName: 'Xizhou Township' },
        { value: '525', text: '竹塘鄉', areaEngName: 'Zhutang Township' },
        { value: '526', text: '二林鎮', areaEngName: 'Erlin Township' },
        { value: '527', text: '大城鄉', areaEngName: 'Dacheng Township' },
        { value: '528', text: '芳苑鄉', areaEngName: 'Fangyuan Township' },
        { value: '530', text: '二水鄉', areaEngName: 'Ershui Township' }
      ]
    },
    {
      text: '南投縣',
      value: '13',
      cityEngName: 'Nantou County',
      children: [
        { value: '540', text: '南投市', areaEngName: 'Nantou City' },
        { value: '541', text: '中寮鄉', areaEngName: 'Zhongliao Township' },
        { value: '542', text: '草屯鎮', areaEngName: 'Caotun Township' },
        { value: '544', text: '國姓鄉', areaEngName: 'Guoxing Township' },
        { value: '545', text: '埔里鎮', areaEngName: 'Puli Township' },
        { value: '546', text: '仁愛鄉', areaEngName: 'Ren’ai Township' },
        { value: '551', text: '名間鄉', areaEngName: 'Mingjian Township' },
        { value: '552', text: '集集鎮', areaEngName: 'Jiji Township' },
        { value: '553', text: '水里鄉', areaEngName: 'Shuili Township' },
        { value: '555', text: '魚池鄉', areaEngName: 'Yuchi Township' },
        { value: '556', text: '信義鄉', areaEngName: 'Xinyi Township' },
        { value: '557', text: '竹山鎮', areaEngName: 'Zhushan Township' },
        { value: '558', text: '鹿谷鄉', areaEngName: 'Lugu Township' }
      ]
    },
    {
      text: '嘉義市',
      value: '14',
      cityEngName: 'Chiayi City',
      children: [
        { value: '600', text: '西區', areaEngName: 'West Dist.' },
        { value: '600', text: '東區', areaEngName: 'East Dist.' }
      ]
    },
    {
      text: '嘉義縣',
      value: '15',
      cityEngName: 'Chiayi County',
      children: [
        { value: '602', text: '番路鄉', areaEngName: 'Fanlu Township' },
        { value: '603', text: '梅山鄉', areaEngName: 'Meishan Township' },
        { value: '604', text: '竹崎鄉', areaEngName: 'Zhuqi Township' },
        { value: '605', text: '阿里山鄉', areaEngName: 'Alishan Township' },
        { value: '606', text: '中埔鄉', areaEngName: 'Zhongpu Township' },
        { value: '607', text: '大埔鄉', areaEngName: 'Dapu Township' },
        { value: '608', text: '水上鄉', areaEngName: 'Shuishang Township' },
        { value: '611', text: '鹿草鄉', areaEngName: 'Lucao Township' },
        { value: '612', text: '太保市', areaEngName: 'Taibao City' },
        { value: '613', text: '朴子市', areaEngName: 'Puzi City' },
        { value: '614', text: '東石鄉', areaEngName: 'Dongshi Township' },
        { value: '615', text: '六腳鄉', areaEngName: 'Liujiao Township' },
        { value: '616', text: '新港鄉', areaEngName: 'Xingang Township' },
        { value: '621', text: '民雄鄉', areaEngName: 'Minxiong Township' },
        { value: '622', text: '大林鎮', areaEngName: 'Dalin Township' },
        { value: '623', text: '溪口鄉', areaEngName: 'Xikou Township' },
        { value: '624', text: '義竹鄉', areaEngName: 'Yizhu Township' },
        { value: '625', text: '布袋鎮', areaEngName: 'Budai Township' }
      ]
    },
    {
      text: '雲林縣',
      value: '16',
      cityEngName: 'Yunlin County',
      children: [
        { value: '630', text: '斗南鎮', areaEngName: 'Dounan Township' },
        { value: '631', text: '大埤鄉', areaEngName: 'Dapi Township' },
        { value: '632', text: '虎尾鎮', areaEngName: 'Huwei Township' },
        { value: '633', text: '土庫鎮', areaEngName: 'Tuku Township' },
        { value: '634', text: '褒忠鄉', areaEngName: 'Baozhong Township' },
        { value: '635', text: '東勢鄉', areaEngName: 'Dongshi Township' },
        { value: '636', text: '臺西鄉', areaEngName: 'Taixi Township' },
        { value: '637', text: '崙背鄉', areaEngName: 'Lunbei Township' },
        { value: '638', text: '麥寮鄉', areaEngName: 'Mailiao Township' },
        { value: '640', text: '斗六市', areaEngName: 'Douliu City' },
        { value: '643', text: '林內鄉', areaEngName: 'Linnei Township' },
        { value: '646', text: '古坑鄉', areaEngName: 'Gukeng Township' },
        { value: '647', text: '莿桐鄉', areaEngName: 'Citong Township' },
        { value: '648', text: '西螺鎮', areaEngName: 'Xiluo Township' },
        { value: '649', text: '二崙鄉', areaEngName: 'Erlun Township' },
        { value: '651', text: '北港鎮', areaEngName: 'Beigang Township' },
        { value: '652', text: '水林鄉', areaEngName: 'Shuilin Township' },
        { value: '653', text: '口湖鄉', areaEngName: 'Kouhu Township' },
        { value: '654', text: '四湖鄉', areaEngName: 'Sihu Township' },
        { value: '655', text: '元長鄉', areaEngName: 'Yuanchang Township' }
      ]
    },
    {
      text: '臺南市',
      value: '17',
      cityEngName: 'Tainan City',
      children: [
        { value: '700', text: '中西區', areaEngName: 'West Central Dist.' },
        { value: '701', text: '東區', areaEngName: 'East Dist.' },
        { value: '702', text: '南區', areaEngName: 'South Dist.' },
        { value: '704', text: '北區', areaEngName: 'North Dist.' },
        { value: '708', text: '安平區', areaEngName: 'Anping Dist.' },
        { value: '709', text: '安南區', areaEngName: 'Annan Dist.' },
        { value: '710', text: '永康區', areaEngName: 'Yongkang Dist.' },
        { value: '711', text: '歸仁區', areaEngName: 'Guiren Dist.' },
        { value: '712', text: '新化區', areaEngName: 'Xinhua Dist.' },
        { value: '713', text: '左鎮區', areaEngName: 'Zuozhen Dist.' },
        { value: '714', text: '玉井區', areaEngName: 'Yujing Dist.' },
        { value: '715', text: '楠西區', areaEngName: 'Nanxi Dist.' },
        { value: '716', text: '南化區', areaEngName: 'Nanhua Dist.' },
        { value: '717', text: '仁德區', areaEngName: 'Rende Dist.' },
        { value: '718', text: '關廟區', areaEngName: 'Guanmiao Dist.' },
        { value: '719', text: '龍崎區', areaEngName: 'Longqi Dist.' },
        { value: '720', text: '官田區', areaEngName: 'Guantian Dist.' },
        { value: '721', text: '麻豆區', areaEngName: 'Madou Dist.' },
        { value: '722', text: '佳里區', areaEngName: 'Jiali Dist.' },
        { value: '723', text: '西港區', areaEngName: 'Xigang Dist.' },
        { value: '724', text: '七股區', areaEngName: 'Qigu Dist.' },
        { value: '725', text: '將軍區', areaEngName: 'Jiangjun Dist.' },
        { value: '726', text: '學甲區', areaEngName: 'Xuejia Dist.' },
        { value: '727', text: '北門區', areaEngName: 'Beimen Dist.' },
        { value: '730', text: '新營區', areaEngName: 'Xinying Dist.' },
        { value: '731', text: '後壁區', areaEngName: 'Houbi Dist.' },
        { value: '732', text: '白河區', areaEngName: 'Baihe Dist.' },
        { value: '733', text: '東山區', areaEngName: 'Dongshan Dist.' },
        { value: '734', text: '六甲區', areaEngName: 'Liujia Dist.' },
        { value: '735', text: '下營區', areaEngName: 'Xiaying Dist.' },
        { value: '736', text: '柳營區', areaEngName: 'Liuying Dist.' },
        { value: '737', text: '鹽水區', areaEngName: 'Yanshui Dist.' },
        { value: '741', text: '善化區', areaEngName: 'Shanhua Dist.' },
        { value: '744', text: '新市區', areaEngName: 'Xinshi Dist.' },
        { value: '742', text: '大內區', areaEngName: 'Danei Dist.' },
        { value: '743', text: '山上區', areaEngName: 'Shanshang Dist.' },
        { value: '745', text: '安定區', areaEngName: 'Anding Dist.' }
      ]
    },
    {
      text: '高雄市',
      value: '18',
      cityEngName: 'Kaohsiung City',
      children: [
        { value: '800', text: '新興區', areaEngName: 'Xinxing Dist.' },
        { value: '801', text: '前金區', areaEngName: 'Qianjin Dist.' },
        { value: '802', text: '苓雅區', areaEngName: 'Lingya Dist.' },
        { value: '803', text: '鹽埕區', areaEngName: 'Yancheng Dist.' },
        { value: '804', text: '鼓山區', areaEngName: 'Gushan Dist.' },
        { value: '805', text: '旗津區', areaEngName: 'Qijin Dist.' },
        { value: '806', text: '前鎮區', areaEngName: 'Qianzhen Dist.' },
        { value: '807', text: '三民區', areaEngName: 'Sanmin Dist.' },
        { value: '811', text: '楠梓區', areaEngName: 'Nanzi Dist.' },
        { value: '812', text: '小港區', areaEngName: 'Xiaogang Dist.' },
        { value: '813', text: '左營區', areaEngName: 'Zuoying Dist.' },
        { value: '814', text: '仁武區', areaEngName: 'Renwu Dist.' },
        { value: '815', text: '大社區', areaEngName: 'Dashe Dist.' },
        { value: '817', text: '東沙群島', areaEngName: 'Dongsha Islands' },
        { value: '819', text: '南沙群島', areaEngName: 'Nansha Islands' },
        { value: '820', text: '岡山區', areaEngName: 'Gangshan Dist.' },
        { value: '821', text: '路竹區', areaEngName: 'Luzhu Dist.' },
        { value: '822', text: '阿蓮區', areaEngName: 'Alian Dist.' },
        { value: '823', text: '田寮區', areaEngName: 'Tianliao Dist.' },
        { value: '824', text: '燕巢區', areaEngName: 'Yanchao Dist.' },
        { value: '825', text: '橋頭區', areaEngName: 'Qiaotou Dist.' },
        { value: '826', text: '梓官區', areaEngName: 'Ziguan Dist.' },
        { value: '827', text: '彌陀區', areaEngName: 'Mituo Dist.' },
        { value: '828', text: '永安區', areaEngName: 'Yong’an Dist.' },
        { value: '829', text: '湖內區', areaEngName: 'Hunei Dist.' },
        { value: '830', text: '鳳山區', areaEngName: 'Fengshan Dist.' },
        { value: '831', text: '大寮區', areaEngName: 'Daliao Dist.' },
        { value: '832', text: '林園區', areaEngName: 'Linyuan Dist.' },
        { value: '833', text: '鳥松區', areaEngName: 'Niaosong Dist.' },
        { value: '840', text: '大樹區', areaEngName: 'Dashu Dist.' },
        { value: '842', text: '旗山區', areaEngName: 'Qishan Dist.' },
        { value: '843', text: '美濃區', areaEngName: 'Meinong Dist.' },
        { value: '844', text: '六龜區', areaEngName: 'Liugui Dist.' },
        { value: '845', text: '內門區', areaEngName: 'Neimen Dist.' },
        { value: '846', text: '杉林區', areaEngName: 'Shanlin Dist.' },
        { value: '847', text: '甲仙區', areaEngName: 'Jiaxian Dist.' },
        { value: '848', text: '桃源區', areaEngName: 'Taoyuan Dist.' },
        { value: '849', text: '那瑪夏區', areaEngName: 'Namaxia Dist.' },
        { value: '851', text: '茂林區', areaEngName: 'Maolin Dist.' },
        { value: '852', text: '茄萣區', areaEngName: 'Qieding Dist.' }
      ]
    },
    {
      text: '南海島',
      value: '19',
      cityEngName: 'Nanhai',
      children: [
        { value: '817', text: '東沙群島', areaEngName: 'Dongsha Islands' },
        { value: '819', text: '南沙群島', areaEngName: 'Nansha Islands' }
      ]
    },
    {
      text: '澎湖縣',
      value: '20',
      cityEngName: 'Penghu County',
      children: [
        { value: '880', text: '馬公市', areaEngName: 'Magong City' },
        { value: '881', text: '西嶼鄉', areaEngName: 'Xiyu Township' },
        { value: '882', text: '望安鄉', areaEngName: 'Wang’an Township' },
        { value: '883', text: '七美鄉', areaEngName: 'Qimei Township' },
        { value: '884', text: '白沙鄉', areaEngName: 'Baisha Township' },
        { value: '885', text: '湖西鄉', areaEngName: 'Huxi Township' }
      ]
    },
    {
      text: '金門縣',
      value: '21',
      cityEngName: 'Kinmen County',
      children: [
        { value: '890', text: '金沙鎮', areaEngName: 'Jinsha Township' },
        { value: '891', text: '金湖鎮', areaEngName: 'Jinhu Township' },
        { value: '892', text: '金寧鄉', areaEngName: 'Jinning Township' },
        { value: '893', text: '金城鎮', areaEngName: 'Jincheng Township' },
        { value: '894', text: '烈嶼鄉', areaEngName: 'Lieyu Township' },
        { value: '896', text: '烏坵鄉', areaEngName: 'Wuqiu Township' }
      ]
    },
    {
      text: '屏東縣',
      value: '22',
      cityEngName: 'Pingtung County',
      children: [
        { value: '900', text: '屏東市', areaEngName: 'Pingtung City' },
        { value: '901', text: '三地門鄉', areaEngName: 'Sandimen Township' },
        { value: '902', text: '霧臺鄉', areaEngName: 'Wutai Township' },
        { value: '903', text: '瑪家鄉', areaEngName: 'Majia Township' },
        { value: '904', text: '九如鄉', areaEngName: 'Jiuru Township' },
        { value: '905', text: '里港鄉', areaEngName: 'Ligang Township' },
        { value: '906', text: '高樹鄉', areaEngName: 'Gaoshu Township' },
        { value: '907', text: '鹽埔鄉', areaEngName: 'Yanpu Township' },
        { value: '908', text: '長治鄉', areaEngName: 'Changzhi Township' },
        { value: '909', text: '麟洛鄉', areaEngName: 'Linluo Township' },
        { value: '911', text: '竹田鄉', areaEngName: 'Zhutian Township' },
        { value: '912', text: '內埔鄉', areaEngName: 'Neipu Township' },
        { value: '913', text: '萬丹鄉', areaEngName: 'Wandan Township' },
        { value: '920', text: '潮州鎮', areaEngName: 'Chaozhou Township' },
        { value: '921', text: '泰武鄉', areaEngName: 'Taiwu Township' },
        { value: '922', text: '來義鄉', areaEngName: 'Laiyi Township' },
        { value: '923', text: '萬巒鄉', areaEngName: 'Wanluan Township' },
        { value: '924', text: '崁頂鄉', areaEngName: 'Kanding Township' },
        { value: '925', text: '新埤鄉', areaEngName: 'Xinpi Township' },
        { value: '926', text: '南州鄉', areaEngName: 'Nanzhou Township' },
        { value: '927', text: '林邊鄉', areaEngName: 'Linbian Township' },
        { value: '928', text: '東港鎮', areaEngName: 'Donggang Township' },
        { value: '929', text: '琉球鄉', areaEngName: 'Liuqiu Township' },
        { value: '931', text: '佳冬鄉', areaEngName: 'Jiadong Township' },
        { value: '932', text: '新園鄉', areaEngName: 'Xinyuan Township' },
        { value: '940', text: '枋寮鄉', areaEngName: 'Fangliao Township' },
        { value: '941', text: '枋山鄉', areaEngName: 'Fangshan Township' },
        { value: '942', text: '春日鄉', areaEngName: 'Chunri Township' },
        { value: '943', text: '獅子鄉', areaEngName: 'Shizi Township' },
        { value: '944', text: '車城鄉', areaEngName: 'Checheng Township' },
        { value: '945', text: '牡丹鄉', areaEngName: 'Mudan Township' },
        { value: '946', text: '恆春鎮', areaEngName: 'Hengchun Township' },
        { value: '947', text: '滿州鄉', areaEngName: 'Manzhou Township' }
      ]
    },
    {
      text: '臺東縣',
      value: '23',
      cityEngName: 'Taitung County',
      children: [
        { value: '950', text: '臺東市', areaEngName: 'Taitung City' },
        { value: '951', text: '綠島鄉', areaEngName: 'Ludao Township' },
        { value: '952', text: '蘭嶼鄉', areaEngName: 'Lanyu Township' },
        { value: '953', text: '延平鄉', areaEngName: 'Yanping Township' },
        { value: '954', text: '卑南鄉', areaEngName: 'Beinan Township' },
        { value: '955', text: '鹿野鄉', areaEngName: 'Luye Township' },
        { value: '956', text: '關山鎮', areaEngName: 'Guanshan Township' },
        { value: '957', text: '海端鄉', areaEngName: 'Haiduan Township' },
        { value: '958', text: '池上鄉', areaEngName: 'Chishang Township' },
        { value: '959', text: '東河鄉', areaEngName: 'Donghe Township' },
        { value: '961', text: '成功鎮', areaEngName: 'Chenggong Township' },
        { value: '962', text: '長濱鄉', areaEngName: 'Changbin Township' },
        { value: '963', text: '太麻里鄉', areaEngName: 'Taimali Township' },
        { value: '964', text: '金峰鄉', areaEngName: 'Jinfeng Township' },
        { value: '965', text: '大武鄉', areaEngName: 'Dawu Township' },
        { value: '966', text: '達仁鄉', areaEngName: 'Daren Township' }
      ]
    },
    {
      text: '花蓮縣',
      value: '24',
      cityEngName: 'Hualien County',
      children: [
        { value: '970', text: '花蓮市', areaEngName: 'Hualien City' },
        { value: '971', text: '新城鄉', areaEngName: 'Xincheng Township' },
        { value: '972', text: '秀林鄉', areaEngName: 'Xiulin Township' },
        { value: '973', text: '吉安鄉', areaEngName: 'Ji’an Township' },
        { value: '974', text: '壽豐鄉', areaEngName: 'Shoufeng Township' },
        { value: '975', text: '鳳林鎮', areaEngName: 'Fenglin Township' },
        { value: '976', text: '光復鄉', areaEngName: 'Guangfu Township' },
        { value: '977', text: '豐濱鄉', areaEngName: 'Fengbin Township' },
        { value: '978', text: '瑞穗鄉', areaEngName: 'Ruisui Township' },
        { value: '979', text: '萬榮鄉', areaEngName: 'Wanrong Township' },
        { value: '981', text: '玉里鎮', areaEngName: 'Yuli Township' },
        { value: '982', text: '卓溪鄉', areaEngName: 'Zhuoxi Township' },
        { value: '983', text: '富里鄉', areaEngName: 'Fuli Township' }
      ]
    }
  ],
  price: [
    { text: '5000以下', value: '5000' },
    { text: '5001~1萬', value: '5001~1萬' },
    { text: '1萬~5萬', value: '1萬~5萬' },
    { text: '5萬~10萬', value: '5萬~10萬' },
    { text: '10萬~30萬', value: '10萬~30萬' },
    { text: '30萬~50萬', value: '30萬~50萬' },
    { text: '50萬~80萬', value: '50萬~80萬' },
    { text: '80~100萬', value: '80萬~100萬' },
    { text: '100萬~300萬', value: '100萬~300萬' },
    { text: '300萬以上', value: '300萬以上' }
  ],
  caseType: [
    { text: '平面設計', value: '平面設計' },
    { text: '網頁設計', value: '網頁設計' },
    { text: '程式開發', value: '程式開發' },
    { text: '翻譯寫作', value: '翻譯寫作 ' },
    { text: '商攝娛樂', value: '商攝娛樂' },
    { text: '影像製作', value: '影像製作' },
    { text: '空間設計', value: '空間設計' },
    { text: '生活服務', value: '生活服務' },
    { text: '活動企劃', value: '活動企劃' },
    { text: '專業顧問', value: '專業顧問' },
    { text: '資訊工程', value: '資訊工程' }
  ],
  experience: [
    { text: '無接案經驗', value: '無接案經驗' },
    { text: '0~1年接案經驗', value: '0~1年接案經驗' },
    { text: '1~3年接案經驗', value: '1~3年接案經驗' },
    { text: '3~5年接案經驗', value: '3~5年接案經驗' },
    { text: '5~10年接案經驗', value: '5~10年接案經驗' },
    { text: '10年以上接案經驗', value: '10年以上接案經驗' }
  ]
})
